language: node_js
node_js:
  - "8"
  - "6"
  - "4"
env:
  global:
    secure: w7GFkzrCxmAn4oWFKO4seeIBwP9uaQBd09sh1RnCPQMF3XMSmHhhA7PEAb4d86LTKvI4uQ5td7Ip6f7B1PR5f1DYZD4QHDd6I7zXTAuRq7ROy7+yEjPuz5aevGn8S0rVsYfjTRaR6kIXntnSH//ugTyKFej7vDMSuXeh0uVInKzoLDPtHKKF7DtziJi0520nRkT0k7NuEIXSinl1eAUJFWHqXjWc8TeCab3xRmd3OUZFkcPunS6zTc5tCZdeqqZgnHtn3DIpwpt2RrJmrN78G919U21FBEf2fYiEbCnlLZUx+Q+8yIJ4koQ8jdGNiYkxwllvZ/dqWajwjqEeS6Ope5SKbrBh2LAxj2J5nxDpV+G05I37mvJEAC6gcN+ax2PfVcYAYmv0oXDA8fEbF+6NT8vKBhwMY8jH9VPgGg27VOzVmA10SlLP/78vp+rR82l+NhzlAzBVmTjCLj7zbjrk/D7QJanOu44HDemnK1ZaOU7nZdQskXBDwSHVt7jdvwuEh+d2iqZQYFeLDR3h98na6LCViEx/whJj2b9tqXMeP3DKkUx46xrThD//SBiTgf9UVrtuS3dzZ4wN5JQeHSrFum+i1cimxZzqVaLAJOh3mz8NsAZ4u74dfch1BiocMYFLpGY+iX027PAXRi3xixdM07pEOE1fTSqMxG13QVDkuz0=
