language: node_js
node_js:
  - "8"
  - "6"
  - "4"
env:
  global:
    secure: fF+gG8CwSAxKwR+7XTpQB5jijK8z9CpsHONAR/+6IrNkWou156QlpDnajBZDEx5GUaufjOMvtYi5VeDAz8UCkcWMY8J0SFLwKhKcGvdHogy2jNx0ooUPko3Zc45zO+T4QS+2aerdmjikSWxfTtKjkgrhl0I3NB2QluOJVxRN9o3NyOVY+1HPOqtMAE6McumXLe9S9oPoM0X8qRd8pGqeCc4/q2/gtybWo5nR6XSZrKzT+g5cF72wzHXzDa9rKSJHWGWG9QLLVsJoC1HToo7E0u4dMqn31gyz9c3zoOmiYbKji5KeIHV8wmX1HbPxudCC+e3oUVJAPFJ6s8S9ge6/Y/fCTtYKqomi/N/h7GLAzT5uPEq6pZy9VCdsL/0j3bpwfCbLd5G0fM3lHpcNpevP8FHv+WkshTHfeXW7C2ydgkWDOXj9iM0ZvrW5rfe3knNTl4VpSyN0pQmQINroXDpPT+c1xjgjhj/jbxBbvZljikw2+UgpBBSJyouTnoKBn/mJ5njNTin+hSnfg2ERwxjUb4H/gRLgO4xHLMCtC6Vv4CESP7uNBU6lhVUXra3tkqw8M/dIILoNP30G4R7tUeg5htaQBPAdC/vS3VLXfTSmJbnt8N7oT9O2FHgbx26BiQTY9evCL7/763yKW7nDdNaSUQlUfVHNxWSls2Qq83TrQkg=
